### ISSUE TITLE
ошибка dev режиме (npm start) Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by akaguny** [mobx-cookbook/mobx-cookbook.github.io#31]
Шаги к воспроизведению:
1. установить зависимости
2. открыть по прямой ссылке страницу с примерами кода / перейти через меню

ОР:
1. открыта страница с примерами кода
2. загрузка страницы окончена
3. интерактивные примеры доступны

ФР:
1. ![image](https://github.com/mobx-cookbook/mobx-cookbook.github.io/assets/3505959/d2a9ee7b-3fe2-4375-a119-59ff6cfa88c0)
2. в консоли
```
index.mjs:76 Uncaught RangeError: Maximum call stack size exceeded
    at FiberNode.hasOwnProperty (<anonymous>)
    at dequal (index.mjs:76:1)
    at dequal (index.mjs:77:1)
    at dequal (index.mjs:77:1)
    at dequal (index.mjs:77:1)
    at dequal (index.mjs:77:1)
    at dequal (index.mjs:77:1)
    at dequal (index.mjs:77:1)
    at dequal (index.mjs:77:1)
    at dequal (index.mjs:77:1)
dequal @ index.mjs:76
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
dequal @ index.mjs:77
setTimeout (async)
eval @ useWindowSize.ts:46
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
eval @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
react_devtools_backend_compact.js:2367 The above error occurred in the <SandpackProvider> component:

    at SandpackProvider (webpack-internal:///./node_modules/@codesandbox/sandpack-react/dist/esm/index.js:1781:26)
    at Sandpack (webpack-internal:///./node_modules/@codesandbox/sandpack-react/dist/esm/index.js:4553:22)
    at div
    at CodeViewer (webpack-internal:///./src/components/code-viewer/index.jsx:7:31)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:154:30)
    at wrapper (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:149:25)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:154:30)
    at MDXContent (webpack-internal:///./docs/mobx-inside.md:14:1587)
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at MDXContent (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/MDXContent/index.js:13:34)
    at div
    at DocItemContent (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/DocItem/Content/index.js:25:315)
    at article
    at div
    at div
    at div
    at DocItemLayout (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/DocItem/Layout/index.js:25:749)
    at HtmlClassNameProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/metadataUtils.js:27:56)
    at DocProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/doc.js:22:35)
    at DocItem (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/DocItem/index.js:15:72)
    at RouteContextProvider (webpack-internal:///./node_modules/@docusaurus/core/lib/client/routeContext.js:14:70)
    at LoadableComponent (webpack-internal:///./node_modules/react-loadable/lib/index.js:138:32)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:460:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:662:29)
    at div
    at main
    at DocPageLayoutMain (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/DocPage/Layout/Main/index.js:14:41)
    at div
    at ErrorBoundary (webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/ErrorBoundary.js:14:246)
    at div
    at NavbarSecondaryMenuDisplayProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/navbarSecondaryMenu/display.js:19:327)
    at NavbarMobileSidebarProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/navbarMobileSidebar.js:21:423)
    at NavbarSecondaryMenuContentProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/navbarSecondaryMenu/content.js:14:156)
    at NavbarProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/navbarUtils.js:20:38)
    at HtmlClassNameProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/metadataUtils.js:27:56)
    at PluginHtmlClassNameProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/metadataUtils.js:30:52)
    at DocsPreferredVersionContextProviderUnsafe (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/docsPreferredVersion.js:31:392)
    at DocsPreferredVersionContextProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/docsPreferredVersion.js:34:60)
    at ScrollControllerProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/scrollUtils.js:18:488)
    at AnnouncementBarProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/announcementBar.js:23:459)
    at ColorModeProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/colorMode.js:25:1255)
    at eval (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/reactUtils.js:65:19)
    at LayoutProvider (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/Layout/Provider/index.js:18:655)
    at Layout (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/Layout/index.js:24:33)
    at DocPageLayout (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/DocPage/Layout/index.js:17:37)
    at DocsSidebarProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/docsSidebar.js:17:43)
    at DocsVersionProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/contexts/docsVersion.js:15:43)
    at HtmlClassNameProvider (webpack-internal:///./node_modules/@docusaurus/theme-common/lib/utils/metadataUtils.js:27:56)
    at DocPage (webpack-internal:///./node_modules/@docusaurus/theme-classic/lib/theme/DocPage/index.js:21:788)
    at RouteContextProvider (webpack-internal:///./node_modules/@docusaurus/core/lib/client/routeContext.js:14:70)
    at LoadableComponent (webpack-internal:///./node_modules/react-loadable/lib/index.js:138:32)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:460:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:662:29)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:460:29)
    at ClientLifecyclesDispatcher (webpack-internal:///./node_modules/@docusaurus/core/lib/client/ClientLifecyclesDispatcher.js:15:271)
    at PendingNavigation (webpack-internal:///./node_modules/@docusaurus/core/lib/client/PendingNavigation.js:15:138)
    at Root (webpack-internal:///./node_modules/@docusaurus/core/lib/client/theme-fallback/Root/index.js:18:25)
    at BrowserContextProvider (webpack-internal:///./node_modules/@docusaurus/core/lib/client/browserContext.js:19:126)
    at DocusaurusContextProvider (webpack-internal:///./node_modules/@docusaurus/core/lib/client/docusaurusContext.js:19:495)
    at ErrorBoundary (webpack-internal:///./node_modules/@docusaurus/core/lib/client/exports/ErrorBoundary.js:14:246)
    at App (webpack-internal:///./node_modules/@docusaurus/core/lib/client/App.js:26:241)
    at Router (webpack-internal:///./node_modules/react-router/esm/react-router.js:79:30)
    at BrowserRouter (webpack-internal:///./node_modules/react-router-dom/esm/react-router-dom.js:57:35)
    at r (webpack-internal:///./node_modules/react-helmet-async/lib/index.module.js:16:7320)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
overrideMethod @ react_devtools_backend_compact.js:2367
logCapturedError @ react-dom.development.js:20085
callback @ react-dom.development.js:20154
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20709
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
eval @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
dispatchAction @ react-dom.development.js:16139
updateWindowSize @ useWindowSize.ts:46
setTimeout (async)
eval @ useWindowSize.ts:46
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
eval @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
```

----
воспроизводится на main ветке, возможно кто-то сталкивался или наоборот всё работает стабильно. Отпишитесь пожалуйста. Буду проверять на разной конфигурации оборудования, если только у меня

**Comment by kubk** [comment]
Какая версия node? На v19.8.1 проблем нет

**Comment by kubk** [comment]
Вообще выглядит как проблема sandpack в связке с docusaurus. Может обновление зависимостей поможет

**Comment by akaguny** [comment]
Возможно, проверил на последней LTS(18x) и current(20x) версиях nodejs, воспроизводится.
Позже попробую обновить зависимости и повторить проверку на LTS
